language: python

python:
  - "3.6"

sudo: required

install:
  # dependencies for mpi4py
  - sudo apt-get install openmpi-bin # libopenmpi-dev
  # other packages to install
  - pip install flake8 .
  - pip install coveralls
  - pip install nose2

before_script:
  - flake8 --show-source

script:
  - python setup.py install
  - nose2 --with-coverage

after_success:
  - coveralls
