language: python

python:
  - "3.6"

os: linux

dist: trusty

sudo: required

install:
  # Setup conda.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export TEST_FLAG="True"

  # Create the h-baselines conda environment.
  - conda env create -f environment.yml
  - source activate h-baselines

  # other packages to install
  - pip install flake8
  - pip install coveralls
  - pip install nose2
  - pip install pydocstyle

#  # third-party tools
#  - ./scripts/install_thirdparty.sh

before_script:
  - flake8 --show-source
#  - pydocstyle . --convention=numpy

script:
  - pip install -e .
  - nose2 --with-coverage

after_success:
  - coveralls
