language: python

python:
  - "3.6"

os: linux

dist: trusty

sudo: required

install:
  # dependencies for mpi4py
  - sudo apt-get install libopenmpi-dev
  - sudo apt-get install openmpi-bin

  # other packages to install
  - pip install flake8
  - pip install coveralls
  - pip install nose2
  - pip install pydocstyle

#  # third-party tools
#  - ./scripts/install_thirdparty.sh

before_script:
  - flake8 --show-source
#  - pydocstyle . --convention=numpy

script:
  - pip install -e .
  - nose2 --with-coverage

after_success:
  - coveralls
