language: python

python:
  - "3.6"

sudo: required

install:
  - pip install flake8 .
  - pip install coveralls
  - pip install nose2

before_script:
  - flake8 --show-source

script:
  - coverage run setup.py test
  - nose2 --with-coverage

after_success:
  - coveralls
