name: h-baselines

dependencies:
    - python==3.6.6
    - numpy==1.16.0
    - tensorflow==1.10.0
    - pip:
        - ray==0.5.3
        - redis==2.10.6
        - stable-baselines==2.2.1
        - gym==0.10.9
        - mujoco-py==1.50.1.68
