name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install flow and sumo dependencies and binaries.
      run: |
        pushd $HOME
        git clone https://github.com/flow-project/flow
        pushd flow
        git checkout aboudy-tmp  # keeping until model-v3 features are added
        pip install --use-deprecated=legacy-resolver -e .
        ./scripts/setup_sumo_ubuntu1604.sh
        source ~/.bashrc
        popd
        popd

    - name: Install multi-world.
      run: |
        pushd $HOME
        git clone https://github.com/vitchyr/multiworld.git
        pushd multiworld
        pip install -e .
        popd
        popd

    - name: Download additional files.
      run: |
        pushd experiments
        wget https://s3.us-east-2.amazonaws.com/aboudy.experiments/h-baselines/warmup.zip
        unzip warmup.zip
        popd

    - name: Other packages to install.
      run: |
        pip install flake8
        pip install coveralls
        pip install nose2
        pip install pydocstyle

    - name: Analysing the code with pylint.
      run: |
        flake8 --show-source
        pydocstyle . --convention=numpy

    - name: Run tests.
      run: |
        export PATH="$HOME/sumo_binaries/bin:$PATH"
        export SUMO_HOME="$HOME/sumo_binaries/bin"
        pip install --use-deprecated=legacy-resolver -e .
        nose2 --with-coverage

    - name: Upload coverage data to coveralls.io
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
        COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io.
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
