name: Run Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Setup conda.
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        export TEST_FLAG="True"
    - name: Create the h-baselines conda environment.
      run: |
        conda env create -f environment.yml
        source activate h-baselines
    - name: Install flow and sumo dependencies and binaries.
      run: |
        pushd $HOME
        git clone https://github.com/flow-project/flow
        pushd flow
        git checkout aboudy-tmp  # keeping until model-v3 features are added
        pip install -e .
        ./scripts/setup_sumo_ubuntu1604.sh
        source ~/.bashrc
        popd
        popd
    - name: Install multi-world.
      run: |
        pushd $HOME
        git clone https://github.com/vitchyr/multiworld.git
        pushd multiworld
        pip install -e .
        popd
        popd
    - name: Install multi-world.
      run: |
        Download additional files.
        pushd experiments
        wget https://s3.us-east-2.amazonaws.com/aboudy.experiments/h-baselines/warmup.zip
        unzip warmup.zip
        popd
    - name: other packages to install
      run: |
        pip install flake8
        pip install coveralls
        pip install nose2
        pip install pydocstyle
    - name: Analysing the code with pylint.
      run: |
        flake8 --show-source
        pydocstyle . --convention=numpy
    - name: Run tests.
      run: |
        pip install -e .
        nose2 --with-coverage
        coveralls
